# docker-compose.yml - QuanthereumX Ecosystem
# Author: Przemek Buczek

version: "3.8"

services:
  api:
    build: ./src
    container_name: quanthereumx_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: quanthereumx_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quanthereumx_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
